export const WeatherActionTypes = Object.freeze({
    FETCH_WEATHER_START: 'FETCH_WEATHER_START',
    FETCH_WEATHER_SUCCESS: 'FETCH_WEATHER_SUCCESS',
    FETCH_WEATHER_FINISH: 'FETCH_WEATHER_FINISH',
    FETCH_WEATHER_ERROR: 'FETCH_WEATHER_ERROR',
});

export const AppActionTypes = Object.freeze({
    IS_LOADING: 'IS_LOADING',
});
